### ISSUE TITLE
seeking_consumer test fails from archive on crates.io

### ISSUE THREAD

**Issue by ignatenkobrain** [Geal/nom#609]
```
	thread 'stream::tests::seeking_consumer' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:906:4
```

I think this is due to assets missing in that archive.

**Comment by ignatenkobrain** [comment]
Also those tests are failing.

```
---- small_test stdout ----
	thread 'small_test' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:906:4

---- big_bunny_test stdout ----
	thread 'big_bunny_test' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:906:4
```

**Comment by Geal** [comment]
the `stream` module was removed
