### ISSUE TITLE
Panic in convert_error on reaching EOF

### ISSUE THREAD

**Issue by Dr-Emann** [Geal/nom#967]
## Prerequisites

- Rust version : rustc 1.35.0 (3c235d560 2019-05-20)
- nom version : 5.0.0-beta3
- nom compilation features used: default

## Test case

```rust
use nom::character::complete::char;
use nom::error::{convert_error, VerboseError};
use nom::IResult;

fn main() {
    let input = "";

    let result: IResult<_, _, VerboseError<&str>> = char('x')(input);
    match result.unwrap_err() {
        nom::Err::Error(e) | nom::Err::Failure(e) => {
            eprintln!("{:?}", e);
            eprintln!("{}", convert_error(input, e));
        }
        nom::Err::Incomplete(_) => {
            unreachable!();
        }
    }
}
```

Result:
```
VerboseError { errors: [("", Char('x'))] }
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:2686:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   9: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:2686
  10: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:2543
  11: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/vec.rs:1677
  12: nom::error::convert_error
             at /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.0.0-beta3/src/error.rs:173
  13: nom_test::main
             at src/main.rs:12
  14: std::rt::lang_start::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  18: std::rt::lang_start
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by Geal** [comment]
thanks, fixed in 3108cb6
